apiVersion: v1
kind: Service
metadata:
  name: svc-contributors
  labels:
    app:  svc-contributors
spec:
  ports:
    - port: 8000
      name:  svc-contributors
  selector:
    app:  svc-contributors
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-contributors
  labels:
    app: svc-contributors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-contributors
  template:
    metadata:
      annotations:
        io.kubernetes.cri.untrusted-workload: "true"
      labels:
        app: svc-contributors
    spec:
      containers:
      - name: svc-contributors
        image: gcr.io/balintp-gcp-lab/svc-contributors
        ports:
        - containerPort: 8000
