apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: true
  artifacts:
  - image: gcr.io/balintp-gcp-lab/svc-contributors
    context: ./backend/svc-contributors
  - image: gcr.io/balintp-gcp-lab/contribwall-ui
    context: ./frontend
    sync:
      'src/App.js': '/usr/src/app/src/App.js'
      'src/index.css': '/usr/src/app/src/index.css'
  tagPolicy:
    dateTime: {}
deploy:
  kubectl:
    manifests:
    - ./backend/svc-contributors/k8s/*
    - ./frontend/k8s/*
